# Data Setup — Pneumonia Chest X-Ray Datasets

**AAI-540-02 Final Project · Group 4 · Standard Medical Models**

This notebook is the first step in the pipeline. It downloads the two public chest X-ray datasets used by the project and uploads them, organized by `source / split / label`, into the project's S3 data lake (`s3://pneumonia-data-set-group-4/raw-images/`).

**Datasets**
1. **Kermany Chest X-Ray (Pneumonia)** — pediatric JPEGs, ~5.8K images, pre-split into `train/val/test` × `NORMAL/PNEUMONIA`. Pulled programmatically via `kagglehub`.
2. **RSNA Pneumonia Detection Challenge** — adult DICOMs, ~30K images with a separate labels CSV. Pulled manually (see notes in Section 4) and split here into `train/val/test` using stratified-ish random sampling on the row index.

**Downstream steps:** preprocessing (`data_preperations*.ipynb` → `img_preprocessing.py`) reads from `raw-images/`, writes normalized PNGs to `preprocessed-images/`, and registers metadata in Athena (`pneumonia_db.image_metadata`).

## 1. Environment Setup

Install pinned `kagglehub` and import the libraries used across the notebook.
`boto3` and `sklearn` are imported in the sections where they're first used.

In [1]:
!pip install kagglehub -q

In [2]:
import os
from pathlib import Path

import pandas as pd
import kagglehub

from config import BUCKET_NAME, RAW_IMAGE_FOLDER

## 2. Download Kermany Chest X-Ray Dataset

Public Kaggle dataset: `paultimothymooney/chest-xray-pneumonia`. JPEGs, pre-split into `train/val/test` × `NORMAL/PNEUMONIA`. `kagglehub` downloads and caches the archive locally under `~/.cache/kagglehub/`.

In [3]:
# Download latest version
path = kagglehub.dataset_download("paultimothymooney/chest-xray-pneumonia")

print("Path to dataset files:", path)

Path to dataset files: /home/sagemaker-user/.cache/kagglehub/datasets/paultimothymooney/chest-xray-pneumonia/versions/2

In [4]:
# Wrap the cache path as a pathlib.Path for easy traversal.
chest_path = Path(path)

### 2.1 Locate the image root

The archive nests an extra `chest_xray/` directory. The actual `train/val/test` folders live two levels deep — bind the true root to `tru_chest_path` for the upload step.

In [5]:
[x for x in (chest_path / 'chest_xray'/ 'chest_xray').iterdir()]

[PosixPath('/home/sagemaker-user/.cache/kagglehub/datasets/paultimothymooney/chest-xray-pneumonia/versions/2/chest_xray/chest_xray/.DS_Store'),
 PosixPath('/home/sagemaker-user/.cache/kagglehub/datasets/paultimothymooney/chest-xray-pneumonia/versions/2/chest_xray/chest_xray/test'),
 PosixPath('/home/sagemaker-user/.cache/kagglehub/datasets/paultimothymooney/chest-xray-pneumonia/versions/2/chest_xray/chest_xray/train'),
 PosixPath('/home/sagemaker-user/.cache/kagglehub/datasets/paultimothymooney/chest-xray-pneumonia/versions/2/chest_xray/chest_xray/val')]

In [6]:
tru_chest_path = chest_path / 'chest_xray' / 'chest_xray'

## 3. Upload Kermany Images to S3

Walk every `.jpeg` under the local cache and upload it to the project bucket, preserving the `split/label/` directory structure. The destination prefix is `raw-images/` — the preprocessing pipeline reads from here.

The first cell below also **creates the S3 bucket if it doesn't exist yet** (idempotent — no-op on re-runs and for graders running the notebook against a pre-provisioned bucket).

**Note:** the RSNA uploads in Section 5 reuse the same `s3` client and bucket name.

In [7]:
import boto3
import botocore

s3 = boto3.client("s3")
bucket = BUCKET_NAME
root_folder = Path(RAW_IMAGE_FOLDER)


def ensure_bucket_exists(s3_client, bucket_name, region):
    """Create the bucket if it doesn't already exist.

    S3 bucket names are globally unique, so a successful head_bucket means we
    own (or at least can access) it; NoSuchBucket / 404 means we should create.
    Note: us-east-1 is the one region where CreateBucketConfiguration must be
    omitted, so we branch on that.
    """
    try:
        s3_client.head_bucket(Bucket=bucket_name)
        print(f"Bucket s3://{bucket_name} already exists.")
        return
    except botocore.exceptions.ClientError as e:
        code = e.response["Error"]["Code"]
        if code not in ("404", "NoSuchBucket"):
            raise

    if region == "us-east-1":
        s3_client.create_bucket(Bucket=bucket_name)
    else:
        s3_client.create_bucket(
            Bucket=bucket_name,
            CreateBucketConfiguration={"LocationConstraint": region},
        )
    print(f"Created bucket s3://{bucket_name}.")


region = boto3.Session().region_name or "us-east-1"
ensure_bucket_exists(s3, bucket, region)

Bucket s3://pneumonia-data-set-am already exists.

In [ ]:
# First, count files so we can render a percentage.
# Note: rglob materializes lazily, but a list() pass over the local cache is cheap.
files = list(tru_chest_path.rglob('*.jpeg'))
total = len(files)
print(f'Uploading {total} JPEG files to s3://{bucket}/{root_folder}/ ...')

for i, file in enumerate(files, start=1):
    s3_dest = root_folder / file.relative_to(tru_chest_path)
    s3.upload_file(str(file), bucket, str(s3_dest))
    # \r overwrites the same line; end='' prevents a newline; flush=True forces an
    # immediate redraw (Jupyter buffers stdout otherwise).
    print(f'\r  [{i}/{total}] {i/total:6.1%}  {s3_dest}', end='', flush=True)

print()  # Final newline so the next cell's output starts on a fresh line.
print(f'Done. Uploaded {total} files.')

## 4. Download RSNA Pneumonia Detection Dataset

RSNA is hosted as a **Kaggle Competition** (`rsna-pneumonia-detection-challenge`), so it requires authenticated API access rather than the public-dataset endpoint used in Section 2. The download is ~3.7 GB of DICOMs and a labels CSV.

**Before you run this section:**
1. Create an API token at https://www.kaggle.com/settings ("Create New Token") — Kaggle returns a token string.
2. Visit https://www.kaggle.com/competitions/rsna-pneumonia-detection-challenge/rules and click **"I Understand and Accept"** — Kaggle returns 401 / 403 on competition data until the rules are accepted by the authenticated account.
3. Install the token in your SageMaker (or local) home directory. In a terminal, replacing `API_TOKEN` with the value from step 1:
   ```bash
   mkdir -p ~/.kaggle && echo "API_TOKEN" > ~/.kaggle/access_token && chmod 600 ~/.kaggle/access_token
   ```
   `kagglehub` discovers the token file automatically — no environment variables and no username needed.

`kagglehub` caches under `~/.cache/kagglehub/`, so re-running this cell after a successful download is a no-op.

In [8]:
# Download (or pick up from the local kagglehub cache).
# Requires that the authenticated account has accepted the RSNA competition rules.
rsna_path_str = kagglehub.competition_download('rsna-pneumonia-detection-challenge')
rsna_path = Path(rsna_path_str)

print(f"RSNA dataset path: {rsna_path}")

Downloading to /home/sagemaker-user/.cache/kagglehub/competitions/rsna-pneumonia-detection-challenge.archive...

  0%|          | 0.00/3.66G [00:00<?, ?B/s]

  0%|          | 7.00M/3.66G [00:00<00:56, 69.5MB/s]

  1%|          | 24.0M/3.66G [00:00<00:29, 130MB/s]

  1%|          | 40.0M/3.66G [00:00<00:26, 147MB/s]

  1%|▏         | 55.0M/3.66G [00:00<00:40, 95.0MB/s]

  2%|▏         | 76.0M/3.66G [00:00<00:30, 127MB/s]

  2%|▏         | 91.0M/3.66G [00:00<00:30, 125MB/s]

  3%|▎         | 105M/3.66G [00:01<00:37, 101MB/s]

  3%|▎         | 122M/3.66G [00:01<00:32, 118MB/s]

  4%|▎         | 135M/3.66G [00:01<00:33, 113MB/s]

  4%|▍         | 155M/3.66G [00:01<00:34, 108MB/s]

  5%|▍         | 178M/3.66G [00:01<00:27, 135MB/s]

  5%|▌         | 196M/3.66G [00:01<00:25, 146MB/s]

  6%|▌         | 212M/3.66G [00:01<00:37, 98.2MB/s]

  6%|▌         | 233M/3.66G [00:02<00:33, 111MB/s]

  7%|▋         | 257M/3.66G [00:02<00:27, 134MB/s]

  7%|▋         | 275M/3.66G [00:02<00:25, 144MB/s]

  8%|▊         | 291M/3.66G [00:02<00:35, 104MB/s]

  8%|▊         | 313M/3.66G [00:02<00:28, 127MB/s]

  9%|▉         | 335M/3.66G [00:02<00:24, 148MB/s]

 10%|▉         | 360M/3.66G [00:02<00:20, 174MB/s]

 10%|█         | 385M/3.66G [00:03<00:18, 194MB/s]

 11%|█         | 411M/3.66G [00:03<00:16, 214MB/s]

 12%|█▏        | 434M/3.66G [00:03<00:16, 214MB/s]

 12%|█▏        | 458M/3.66G [00:03<00:15, 224MB/s]

 13%|█▎        | 483M/3.66G [00:03<00:14, 232MB/s]

 14%|█▎        | 507M/3.66G [00:03<00:14, 237MB/s]

 14%|█▍        | 531M/3.66G [00:03<00:15, 221MB/s]

 15%|█▍        | 553M/3.66G [00:03<00:17, 192MB/s]

 15%|█▌        | 573M/3.66G [00:03<00:17, 187MB/s]

 16%|█▌        | 592M/3.66G [00:04<00:19, 174MB/s]

 16%|█▋        | 610M/3.66G [00:04<00:25, 130MB/s]

 17%|█▋        | 633M/3.66G [00:04<00:21, 152MB/s]

 17%|█▋        | 654M/3.66G [00:04<00:19, 167MB/s]

 18%|█▊        | 675M/3.66G [00:04<00:17, 179MB/s]

 19%|█▊        | 694M/3.66G [00:04<00:20, 160MB/s]

 19%|█▉        | 720M/3.66G [00:04<00:17, 187MB/s]

 20%|█▉        | 740M/3.66G [00:06<01:12, 43.7MB/s]

 20%|██        | 754M/3.66G [00:07<01:35, 33.0MB/s]

 21%|██        | 780M/3.66G [00:07<01:04, 48.6MB/s]

 21%|██        | 795M/3.66G [00:07<00:59, 51.9MB/s]

 22%|██▏       | 808M/3.66G [00:07<00:54, 56.2MB/s]

 22%|██▏       | 821M/3.66G [00:07<00:47, 65.1MB/s]

 23%|██▎       | 848M/3.66G [00:07<00:31, 95.7MB/s]

 23%|██▎       | 864M/3.66G [00:08<00:42, 71.8MB/s]

 24%|██▎       | 884M/3.66G [00:08<00:33, 90.6MB/s]

 24%|██▍       | 905M/3.66G [00:08<00:26, 111MB/s]

 25%|██▍       | 927M/3.66G [00:08<00:24, 123MB/s]

 25%|██▌       | 943M/3.66G [00:09<01:04, 45.8MB/s]

 25%|██▌       | 955M/3.66G [00:09<01:03, 45.9MB/s]

 26%|██▌       | 971M/3.66G [00:10<00:50, 57.6MB/s]

 26%|██▌       | 983M/3.66G [00:12<02:34, 18.8MB/s]

 27%|██▋       | 995M/3.66G [00:12<02:02, 23.5MB/s]

 27%|██▋       | 0.98G/3.66G [00:12<01:51, 25.8MB/s]

 27%|██▋       | 0.99G/3.66G [00:13<02:54, 16.5MB/s]

 27%|██▋       | 0.99G/3.66G [00:13<02:38, 18.1MB/s]

 27%|██▋       | 1.00G/3.66G [00:13<02:20, 20.3MB/s]

 27%|██▋       | 1.00G/3.66G [00:14<02:10, 21.9MB/s]

 28%|██▊       | 1.01G/3.66G [00:14<01:33, 30.4MB/s]

 28%|██▊       | 1.02G/3.66G [00:14<02:31, 18.8MB/s]

 28%|██▊       | 1.02G/3.66G [00:15<03:23, 13.9MB/s]

 28%|██▊       | 1.03G/3.66G [00:15<02:54, 16.2MB/s]

 28%|██▊       | 1.03G/3.66G [00:15<02:33, 18.4MB/s]

 28%|██▊       | 1.03G/3.66G [00:16<02:25, 19.4MB/s]

 28%|██▊       | 1.04G/3.66G [00:16<02:17, 20.5MB/s]

 28%|██▊       | 1.04G/3.66G [00:16<01:42, 27.5MB/s]

 29%|██▊       | 1.05G/3.66G [00:16<01:49, 25.6MB/s]

 29%|██▊       | 1.05G/3.66G [00:16<01:26, 32.5MB/s]

 29%|██▉       | 1.06G/3.66G [00:17<02:31, 18.5MB/s]

 29%|██▉       | 1.06G/3.66G [00:17<03:25, 13.6MB/s]

 29%|██▉       | 1.07G/3.66G [00:17<01:46, 26.1MB/s]

 29%|██▉       | 1.08G/3.66G [00:18<03:15, 14.2MB/s]

 30%|██▉       | 1.08G/3.66G [00:18<03:09, 14.6MB/s]

 30%|██▉       | 1.09G/3.66G [00:19<02:40, 17.2MB/s]

 30%|██▉       | 1.09G/3.66G [00:19<03:13, 14.3MB/s]

 30%|██▉       | 1.09G/3.66G [00:20<04:09, 11.1MB/s]

 30%|███       | 1.10G/3.66G [00:20<02:26, 18.8MB/s]

 30%|███       | 1.11G/3.66G [00:20<02:20, 19.6MB/s]

 30%|███       | 1.12G/3.66G [00:20<01:40, 27.1MB/s]

 31%|███       | 1.12G/3.66G [00:20<01:27, 31.1MB/s]

 31%|███       | 1.13G/3.66G [00:20<01:16, 35.6MB/s]

 31%|███       | 1.14G/3.66G [00:21<00:52, 51.5MB/s]

 31%|███▏      | 1.15G/3.66G [00:22<03:19, 13.6MB/s]

 31%|███▏      | 1.15G/3.66G [00:22<02:57, 15.2MB/s]

 32%|███▏      | 1.16G/3.66G [00:23<02:38, 16.9MB/s]

 32%|███▏      | 1.16G/3.66G [00:23<02:26, 18.4MB/s]

 32%|███▏      | 1.17G/3.66G [00:23<01:49, 24.5MB/s]

 32%|███▏      | 1.17G/3.66G [00:23<01:34, 28.2MB/s]

 32%|███▏      | 1.18G/3.66G [00:23<01:24, 31.7MB/s]

 32%|███▏      | 1.19G/3.66G [00:23<01:30, 29.5MB/s]

 33%|███▎      | 1.19G/3.66G [00:24<03:10, 13.9MB/s]

 33%|███▎      | 1.20G/3.66G [00:25<03:17, 13.4MB/s]

 33%|███▎      | 1.20G/3.66G [00:25<02:44, 16.1MB/s]

 33%|███▎      | 1.20G/3.66G [00:25<03:46, 11.7MB/s]

 33%|███▎      | 1.21G/3.66G [00:26<04:25, 9.94MB/s]

 33%|███▎      | 1.21G/3.66G [00:26<02:32, 17.2MB/s]

 33%|███▎      | 1.22G/3.66G [00:26<01:54, 22.8MB/s]

 33%|███▎      | 1.22G/3.66G [00:27<02:55, 14.9MB/s]

 34%|███▎      | 1.23G/3.66G [00:27<03:57, 11.0MB/s]

 34%|███▎      | 1.23G/3.66G [00:28<03:59, 10.9MB/s]

 34%|███▎      | 1.23G/3.66G [00:28<03:57, 11.0MB/s]

 34%|███▍      | 1.24G/3.66G [00:28<03:43, 11.6MB/s]

 34%|███▍      | 1.24G/3.66G [00:29<05:21, 8.08MB/s]

 34%|███▍      | 1.24G/3.66G [00:29<05:21, 8.09MB/s]

 34%|███▍      | 1.24G/3.66G [00:29<05:12, 8.31MB/s]

 34%|███▍      | 1.25G/3.66G [00:29<03:40, 11.8MB/s]

 34%|███▍      | 1.25G/3.66G [00:30<02:33, 16.9MB/s]

 34%|███▍      | 1.26G/3.66G [00:30<02:16, 19.0MB/s]

 34%|███▍      | 1.26G/3.66G [00:30<03:34, 12.1MB/s]

 34%|███▍      | 1.26G/3.66G [00:31<04:29, 9.55MB/s]

 35%|███▍      | 1.27G/3.66G [00:31<02:48, 15.3MB/s]

 35%|███▍      | 1.27G/3.66G [00:31<02:06, 20.2MB/s]

 35%|███▍      | 1.28G/3.66G [00:31<01:38, 26.1MB/s]

 35%|███▌      | 1.29G/3.66G [00:31<01:10, 36.2MB/s]

 35%|███▌      | 1.29G/3.66G [00:31<01:07, 37.7MB/s]

 35%|███▌      | 1.30G/3.66G [00:32<02:50, 14.9MB/s]

 35%|███▌      | 1.30G/3.66G [00:32<02:35, 16.3MB/s]

 36%|███▌      | 1.30G/3.66G [00:33<02:41, 15.7MB/s]

 36%|███▌      | 1.31G/3.66G [00:33<01:50, 22.9MB/s]

 36%|███▌      | 1.32G/3.66G [00:33<01:42, 24.6MB/s]

 36%|███▌      | 1.33G/3.66G [00:33<01:26, 29.1MB/s]

 36%|███▋      | 1.34G/3.66G [00:34<01:23, 30.0MB/s]

 37%|███▋      | 1.34G/3.66G [00:34<02:35, 16.0MB/s]

 37%|███▋      | 1.35G/3.66G [00:35<01:47, 23.1MB/s]

 37%|███▋      | 1.35G/3.66G [00:35<01:46, 23.2MB/s]

 37%|███▋      | 1.36G/3.66G [00:35<01:54, 21.6MB/s]

 37%|███▋      | 1.36G/3.66G [00:36<03:14, 12.7MB/s]

 37%|███▋      | 1.37G/3.66G [00:36<02:45, 14.9MB/s]

 38%|███▊      | 1.38G/3.66G [00:36<01:58, 20.6MB/s]

 38%|███▊      | 1.39G/3.66G [00:37<01:27, 27.8MB/s]

 38%|███▊      | 1.40G/3.66G [00:37<01:27, 27.8MB/s]

 38%|███▊      | 1.40G/3.66G [00:37<01:09, 35.0MB/s]

 38%|███▊      | 1.41G/3.66G [00:37<01:11, 33.9MB/s]

 39%|███▊      | 1.42G/3.66G [00:37<01:09, 34.8MB/s]

 39%|███▉      | 1.43G/3.66G [00:37<00:54, 43.9MB/s]

 40%|███▉      | 1.45G/3.66G [00:38<00:29, 79.7MB/s]

 40%|███▉      | 1.46G/3.66G [00:38<00:31, 74.7MB/s]

 40%|████      | 1.47G/3.66G [00:38<00:34, 67.3MB/s]

 40%|████      | 1.48G/3.66G [00:39<01:34, 24.9MB/s]

 41%|████      | 1.49G/3.66G [00:39<01:07, 34.5MB/s]

 41%|████      | 1.50G/3.66G [00:39<00:58, 39.4MB/s]

 41%|████▏     | 1.51G/3.66G [00:39<00:48, 47.8MB/s]

 42%|████▏     | 1.53G/3.66G [00:40<00:34, 66.1MB/s]

 42%|████▏     | 1.55G/3.66G [00:40<00:35, 64.8MB/s]

 43%|████▎     | 1.57G/3.66G [00:40<00:26, 84.0MB/s]

 43%|████▎     | 1.58G/3.66G [00:40<00:23, 96.8MB/s]

 44%|████▍     | 1.60G/3.66G [00:40<00:19, 111MB/s]

 44%|████▍     | 1.62G/3.66G [00:40<00:18, 118MB/s]

 45%|████▍     | 1.64G/3.66G [00:40<00:14, 146MB/s]

 45%|████▌     | 1.66G/3.66G [00:41<00:16, 128MB/s]

 46%|████▌     | 1.68G/3.66G [00:41<00:13, 152MB/s]

 46%|████▋     | 1.70G/3.66G [00:41<00:18, 115MB/s]

 47%|████▋     | 1.72G/3.66G [00:41<00:14, 148MB/s]

 48%|████▊     | 1.74G/3.66G [00:41<00:14, 138MB/s]

 48%|████▊     | 1.76G/3.66G [00:41<00:14, 143MB/s]

 48%|████▊     | 1.77G/3.66G [00:42<00:13, 146MB/s]

 49%|████▉     | 1.79G/3.66G [00:42<00:13, 146MB/s]

 50%|████▉     | 1.82G/3.66G [00:42<00:11, 171MB/s]

 50%|█████     | 1.83G/3.66G [00:42<00:14, 135MB/s]

 51%|█████     | 1.85G/3.66G [00:42<00:14, 139MB/s]

 51%|█████▏    | 1.88G/3.66G [00:42<00:11, 166MB/s]

 52%|█████▏    | 1.89G/3.66G [00:42<00:12, 155MB/s]

 52%|█████▏    | 1.92G/3.66G [00:42<00:10, 174MB/s]

 53%|█████▎    | 1.94G/3.66G [00:43<00:09, 193MB/s]

 54%|█████▎    | 1.96G/3.66G [00:43<00:11, 153MB/s]

 54%|█████▍    | 1.99G/3.66G [00:43<00:10, 178MB/s]

 55%|█████▍    | 2.00G/3.66G [00:43<00:10, 171MB/s]

 55%|█████▌    | 2.03G/3.66G [00:43<00:09, 181MB/s]

 56%|█████▌    | 2.04G/3.66G [00:43<00:09, 187MB/s]

 56%|█████▋    | 2.07G/3.66G [00:43<00:08, 195MB/s]

 57%|█████▋    | 2.08G/3.66G [00:44<00:10, 156MB/s]

 57%|█████▋    | 2.11G/3.66G [00:44<00:09, 170MB/s]

 58%|█████▊    | 2.13G/3.66G [00:44<00:08, 200MB/s]

 59%|█████▉    | 2.16G/3.66G [00:44<00:07, 214MB/s]

 60%|█████▉    | 2.18G/3.66G [00:44<00:06, 235MB/s]

 60%|██████    | 2.21G/3.66G [00:44<00:06, 242MB/s]

 61%|██████    | 2.23G/3.66G [00:44<00:08, 179MB/s]

 62%|██████▏   | 2.25G/3.66G [00:44<00:08, 187MB/s]

 62%|██████▏   | 2.28G/3.66G [00:44<00:07, 200MB/s]

 63%|██████▎   | 2.30G/3.66G [00:45<00:08, 181MB/s]

 63%|██████▎   | 2.32G/3.66G [00:45<00:12, 117MB/s]

 64%|██████▍   | 2.34G/3.66G [00:45<00:10, 137MB/s]

 64%|██████▍   | 2.36G/3.66G [00:45<00:09, 155MB/s]

 65%|██████▌   | 2.38G/3.66G [00:45<00:08, 167MB/s]

 66%|██████▌   | 2.40G/3.66G [00:45<00:08, 167MB/s]

 66%|██████▌   | 2.42G/3.66G [00:46<00:07, 169MB/s]

 66%|██████▋   | 2.43G/3.66G [00:46<00:08, 150MB/s]

 67%|██████▋   | 2.45G/3.66G [00:46<00:11, 116MB/s]

 67%|██████▋   | 2.47G/3.66G [00:46<00:09, 133MB/s]

 68%|██████▊   | 2.49G/3.66G [00:46<00:08, 149MB/s]

 68%|██████▊   | 2.51G/3.66G [00:46<00:07, 162MB/s]

 69%|██████▉   | 2.53G/3.66G [00:46<00:06, 181MB/s]

 70%|██████▉   | 2.55G/3.66G [00:46<00:06, 195MB/s]

 70%|███████   | 2.57G/3.66G [00:47<00:07, 159MB/s]

 71%|███████   | 2.60G/3.66G [00:47<00:05, 191MB/s]

 72%|███████▏  | 2.62G/3.66G [00:47<00:06, 171MB/s]

 72%|███████▏  | 2.65G/3.66G [00:47<00:05, 198MB/s]

 73%|███████▎  | 2.67G/3.66G [00:47<00:04, 215MB/s]

 74%|███████▎  | 2.70G/3.66G [00:47<00:05, 184MB/s]

 74%|███████▍  | 2.72G/3.66G [00:47<00:05, 199MB/s]

 75%|███████▍  | 2.74G/3.66G [00:48<00:05, 171MB/s]

 75%|███████▌  | 2.76G/3.66G [00:48<00:05, 181MB/s]

 76%|███████▌  | 2.78G/3.66G [00:48<00:04, 191MB/s]

 77%|███████▋  | 2.80G/3.66G [00:48<00:05, 173MB/s]

 77%|███████▋  | 2.82G/3.66G [00:48<00:04, 182MB/s]

 78%|███████▊  | 2.84G/3.66G [00:48<00:04, 177MB/s]

 78%|███████▊  | 2.86G/3.66G [00:48<00:04, 188MB/s]

 79%|███████▊  | 2.88G/3.66G [00:48<00:04, 176MB/s]

 79%|███████▉  | 2.90G/3.66G [00:48<00:04, 179MB/s]

 80%|███████▉  | 2.92G/3.66G [00:49<00:05, 151MB/s]

 80%|████████  | 2.93G/3.66G [00:49<00:05, 142MB/s]

 80%|████████  | 2.95G/3.66G [00:49<00:05, 145MB/s]

 81%|████████  | 2.96G/3.66G [00:49<00:04, 155MB/s]

 81%|████████▏ | 2.98G/3.66G [00:49<00:04, 154MB/s]

 82%|████████▏ | 3.00G/3.66G [00:49<00:04, 169MB/s]

 82%|████████▏ | 3.02G/3.66G [00:49<00:03, 174MB/s]

 83%|████████▎ | 3.03G/3.66G [00:49<00:03, 177MB/s]

 83%|████████▎ | 3.06G/3.66G [00:50<00:03, 194MB/s]

 84%|████████▍ | 3.08G/3.66G [00:50<00:03, 182MB/s]

 84%|████████▍ | 3.09G/3.66G [00:50<00:03, 183MB/s]

 85%|████████▍ | 3.11G/3.66G [00:50<00:04, 131MB/s]

 86%|████████▌ | 3.13G/3.66G [00:50<00:03, 159MB/s]

 86%|████████▌ | 3.15G/3.66G [00:50<00:03, 170MB/s]

 87%|████████▋ | 3.17G/3.66G [00:50<00:03, 165MB/s]

 87%|████████▋ | 3.19G/3.66G [00:50<00:02, 181MB/s]

 88%|████████▊ | 3.21G/3.66G [00:51<00:02, 184MB/s]

 88%|████████▊ | 3.23G/3.66G [00:51<00:02, 189MB/s]

 89%|████████▉ | 3.26G/3.66G [00:51<00:02, 205MB/s]

 89%|████████▉ | 3.28G/3.66G [00:51<00:02, 172MB/s]

 90%|████████▉ | 3.29G/3.66G [00:51<00:02, 159MB/s]

 91%|█████████ | 3.32G/3.66G [00:51<00:03, 115MB/s]

 91%|█████████ | 3.34G/3.66G [00:51<00:02, 138MB/s]

 92%|█████████▏| 3.36G/3.66G [00:52<00:02, 124MB/s]

 92%|█████████▏| 3.38G/3.66G [00:52<00:02, 145MB/s]

 93%|█████████▎| 3.40G/3.66G [00:52<00:01, 163MB/s]

 93%|█████████▎| 3.42G/3.66G [00:52<00:01, 147MB/s]

 94%|█████████▍| 3.44G/3.66G [00:52<00:01, 168MB/s]

 95%|█████████▍| 3.46G/3.66G [00:52<00:01, 185MB/s]

 95%|█████████▌| 3.49G/3.66G [00:52<00:00, 201MB/s]

 96%|█████████▌| 3.51G/3.66G [00:52<00:00, 195MB/s]

 96%|█████████▋| 3.53G/3.66G [00:53<00:00, 207MB/s]

 97%|█████████▋| 3.55G/3.66G [00:53<00:00, 141MB/s]

 98%|█████████▊| 3.57G/3.66G [00:53<00:00, 161MB/s]

 98%|█████████▊| 3.59G/3.66G [00:53<00:00, 175MB/s]

 99%|█████████▊| 3.62G/3.66G [00:53<00:00, 191MB/s]

 99%|█████████▉| 3.64G/3.66G [00:54<00:00, 115MB/s]

100%|█████████▉| 3.66G/3.66G [00:54<00:00, 137MB/s]

100%|██████████| 3.66G/3.66G [00:54<00:00, 72.6MB/s]

Extracting files...

RSNA dataset path: /home/sagemaker-user/.cache/kagglehub/competitions/rsna-pneumonia-detection-challenge

In [9]:
# Sanity-check the archive contents. Section 5 expects these specific files to exist.
expected = [
    'stage_2_train_labels.csv',
    'stage_2_train_images',
    'stage_2_test_images',
]
missing = [name for name in expected if not (rsna_path / name).exists()]
if missing:
    raise FileNotFoundError(f"RSNA archive is missing expected files: {missing}")

print("RSNA archive contents:")
for p in sorted(rsna_path.iterdir()):
    print(f"  {p.name}")

RSNA archive contents:
  GCP Credits Request Link - RSNA.txt
  stage_2_detailed_class_info.csv
  stage_2_sample_submission.csv
  stage_2_test_images
  stage_2_train_images
  stage_2_train_labels.csv

## 5. Split RSNA and Upload to S3

RSNA arrives as a flat directory of `.dcm` files plus a single `stage_2_train_labels.csv` mapping `patientId → Target` (0 = normal, 1 = pneumonia). To match the Kermany layout we:

1. Random-split the row index into 80/10/10 train/val/test.
2. Map each row to its split folder and to a `NORMAL`/`PNEUMONIA` target folder.
3. Resolve each `patientId` to the on-disk `.dcm` path.
4. Upload to `s3://pneumonia-data-set-group-4/raw-images/<split>/<label>/<patientId>.dcm`.

_The downstream preprocessing notebook re-stratifies into the final 40/10/10/40 train/val/test/production split — this split is just to mirror the Kermany folder shape._

In [10]:
# Reuse the path produced by Section 4's kagglehub.competition_download call.
set_2_path = rsna_path

In [11]:
[p for p in set_2_path.iterdir()]

[PosixPath('/home/sagemaker-user/.cache/kagglehub/competitions/rsna-pneumonia-detection-challenge/GCP Credits Request Link - RSNA.txt'),
 PosixPath('/home/sagemaker-user/.cache/kagglehub/competitions/rsna-pneumonia-detection-challenge/stage_2_detailed_class_info.csv'),
 PosixPath('/home/sagemaker-user/.cache/kagglehub/competitions/rsna-pneumonia-detection-challenge/stage_2_sample_submission.csv'),
 PosixPath('/home/sagemaker-user/.cache/kagglehub/competitions/rsna-pneumonia-detection-challenge/stage_2_test_images'),
 PosixPath('/home/sagemaker-user/.cache/kagglehub/competitions/rsna-pneumonia-detection-challenge/stage_2_train_images'),
 PosixPath('/home/sagemaker-user/.cache/kagglehub/competitions/rsna-pneumonia-detection-challenge/stage_2_train_labels.csv')]

### 5.1 Load labels and assign train/val/test splits

In [12]:
# stage_2_train_labels.csv maps patientId -> {x, y, width, height, Target}
# (bounding boxes are NaN for negative cases).
df = pd.read_csv(set_2_path / 'stage_2_train_labels.csv')

In [13]:
df.head(2)

                              patientId   x   y  width  height  Target
0  0004cfab-14fd-4e49-80ba-63a80b6bddd6 NaN NaN    NaN     NaN       0
1  00313ee0-9eaa-42f4-b0ab-c148ed3241cd NaN NaN    NaN     NaN       0

In [14]:
from sklearn.model_selection import train_test_split

# 80/10/10 split on the row index. A fixed random_state would make this reproducible;
# left unseeded here because the canonical split is re-derived downstream in CNN_Model.ipynb.
index = list(df.index)
train_index, test_val_index = train_test_split(index, test_size=0.2)
test_index, val_index = train_test_split(test_val_index, test_size=0.5)

# Build a single index -> split mapping for vectorized assignment.
folder_map = {}
for i in train_index:
    folder_map[i] = 'train'
for i in val_index:
    folder_map[i] = 'val'
for i in test_index:
    folder_map[i] = 'test'

df['folder'] = df.index.map(folder_map)

In [15]:
df.folder.value_counts()

folder
train    24181
val       3023
test      3023
Name: count, dtype: int64

### 5.2 Resolve each `patientId` to its DICOM path and assign label folder

In [16]:
# Build patientId -> local .dcm path lookup from the on-disk archive.
img_path_map = {p.stem: p for p in set_2_path.rglob('*.dcm')}

df['local_path'] = df.patientId.map(img_path_map)

In [17]:
# Match the Kermany folder convention: 0 -> NORMAL, 1 -> PNEUMONIA.
target_map = {0: 'NORMAL', 1: 'PNEUMONIA'}
df['target_folder'] = df.Target.map(target_map)

In [18]:
df.head(2)

,patientId,x,y,width,height,Target,folder,local_path,target_folder
0,0004cfab-14fd-4e49-80ba-63a80b6bddd6,NaN,NaN,NaN,NaN,0,train,/home/sagemaker-user/.cache/kagglehub/competit...,NORMAL
1,00313ee0-9eaa-42f4-b0ab-c148ed3241cd,NaN,NaN,NaN,NaN,0,train,/home/sagemaker-user/.cache/kagglehub/competit...,NORMAL

In [19]:
len(df)

30227

### 5.3 Upload RSNA DICOMs to S3

Reuses the `s3` client and `bucket` defined in Section 3. Destination layout matches Kermany: `raw-images/<split>/<label>/<patientId>.dcm`.

In [20]:
rows = df.to_dict(orient='records')
total = len(rows)
print(f'Uploading {total} DICOM files to s3://{bucket}/{root_folder}/ ...')

# RSNA has ~30K files, so we throttle redraws to every 100 iterations
# (plus the final one) to keep the notebook output manageable.
REDRAW_EVERY = 100

for i, row in enumerate(rows, start=1):
    local_path = row['local_path']
    s3_dest = root_folder / row['folder'] / row['target_folder'] / local_path.name
    s3.upload_file(str(local_path), bucket, str(s3_dest))

    if i % REDRAW_EVERY == 0 or i == total:
        print(f'\r  [{i}/{total}] {i/total:6.1%}  {s3_dest}', end='', flush=True)

print()  # Final newline so the next cell's output starts cleanly.
print(f'Done. Uploaded {total} files.')

Uploading 30227 DICOM files to s3://pneumonia-data-set-am/raw-images/ ...

  [100/30227]   0.3%  raw-images/train/NORMAL/024cff3e-86d2-4658-b204-79b94b74b94f.dcm

  [200/30227]   0.7%  raw-images/train/NORMAL/05e79372-5e61-4957-bedf-c2c51a0757ad.dcm

  [300/30227]   1.0%  raw-images/train/PNEUMONIA/06b52ffd-71b8-429a-a284-bb39240ed343.dcm

  [400/30227]   1.3%  raw-images/train/NORMAL/074aea8f-d454-4590-9178-3183dbddcf30.dcm

  [500/30227]   1.7%  raw-images/train/NORMAL/081e308c-0134-4ba3-b745-f632e37a83a1.dcm

  [600/30227]   2.0%  raw-images/train/PNEUMONIA/08e84251-b9cc-47e7-9486-be7becdd1d84.dcm

  [700/30227]   2.3%  raw-images/train/PNEUMONIA/098e14d4-3205-4c2d-a059-738f830c0aa5.dcm

  [800/30227]   2.6%  raw-images/train/NORMAL/0a7b13a9-bcfe-4a99-b699-4c8cf6882f04.dcm

  [900/30227]   3.0%  raw-images/train/NORMAL/0b4f8335-8b99-468e-8556-4190522e8f3b.dcm

  [1000/30227]   3.3%  raw-images/test/NORMAL/0bf4e2be-e95c-4e59-8cd4-db3def008067.dcm

  [1100/30227]   3.6%  raw-images/train/NORMAL/0cb6fe57-ead1-444b-8563-a51f14014e2d.dcm

  [1200/30227]   4.0%  raw-images/train/PNEUMONIA/0f831256-0a69-4fe5-9719-1563d2b6b7b9.dcm

  [1300/30227]   4.3%  raw-images/train/NORMAL/1444c58d-80d7-4262-9cc6-9a7af55f43b7.dcm

  [1400/30227]   4.6%  raw-images/train/PNEUMONIA/15cc8c22-055e-4e64-8c5f-38816f82daa0.dcm

  [1500/30227]   5.0%  raw-images/train/NORMAL/16775991-c274-45ad-8413-6c3382db4418.dcm

  [1600/30227]   5.3%  raw-images/train/PNEUMONIA/175c8be2-76a4-469b-9595-ed33ecedb3cb.dcm

  [1700/30227]   5.6%  raw-images/val/NORMAL/18106833-c6ca-4dfc-88e0-67ff7c7f6746.dcm

  [1800/30227]   6.0%  raw-images/val/NORMAL/18e40369-e039-45bb-a1cd-942e1f5b467c.dcm

  [1900/30227]   6.3%  raw-images/train/PNEUMONIA/1b4ccf65-5872-4694-b441-599471b7794a.dcm

  [2000/30227]   6.6%  raw-images/val/PNEUMONIA/20ed5a77-bb84-4c95-b126-714bd59cdfbf.dcm

  [2100/30227]   6.9%  raw-images/train/NORMAL/25da2f07-bba7-4645-b36a-eb16de62eab7.dcm

  [2200/30227]   7.3%  raw-images/test/NORMAL/2b0fe1f0-e5e8-41b1-8d57-270cc19c5961.dcm

  [2300/30227]   7.6%  raw-images/train/PNEUMONIA/306ff5d4-1ea2-4ce1-9fc7-25a98fac5148.dcm

  [2400/30227]   7.9%  raw-images/test/NORMAL/31a8e5e3-71f6-47cf-8a67-ef4480f62d39.dcm

  [2500/30227]   8.3%  raw-images/train/PNEUMONIA/3246006e-f323-43c9-a322-4979fdb85f37.dcm

  [2600/30227]   8.6%  raw-images/train/PNEUMONIA/32dbe7f3-6c0d-4320-9c89-775dbbb933e8.dcm

  [2700/30227]   8.9%  raw-images/train/NORMAL/339c5854-b7d5-468e-9a0c-6410c3b13e65.dcm

  [2800/30227]   9.3%  raw-images/train/NORMAL/344486d7-255d-433e-8289-b522ed00f838.dcm

  [2900/30227]   9.6%  raw-images/train/PNEUMONIA/34d36b9f-af87-4891-b001-6dc4f5379cb2.dcm

  [3000/30227]   9.9%  raw-images/val/PNEUMONIA/35705250-dc4c-408b-8caf-237bd857ae52.dcm

  [3100/30227]  10.3%  raw-images/train/NORMAL/36246c67-f3b0-4a3f-abd7-5001c1e24cb8.dcm

  [3200/30227]  10.6%  raw-images/train/PNEUMONIA/36d7ebd2-a4e5-42d1-bde0-c7699da0b152.dcm

  [3300/30227]  10.9%  raw-images/test/NORMAL/37731818-2afa-4a22-bd18-db49152ae9b7.dcm

  [3400/30227]  11.2%  raw-images/train/NORMAL/38236bf5-3764-46cc-955b-a55238db74a6.dcm

  [3500/30227]  11.6%  raw-images/train/NORMAL/38bc3079-03e2-49fc-b73f-bb0236c3a676.dcm

  [3600/30227]  11.9%  raw-images/test/PNEUMONIA/395cb95f-700c-4a77-89f1-dcbddf957552.dcm

  [3700/30227]  12.2%  raw-images/train/PNEUMONIA/3a146de9-9044-4abc-b15c-e7e0d18a0704.dcm

  [3800/30227]  12.6%  raw-images/train/PNEUMONIA/3ab3b6ca-609a-4d1b-99b2-571528e637e8.dcm

  [3900/30227]  12.9%  raw-images/train/PNEUMONIA/3b636d43-b04f-4609-9af5-d987d3e12f98.dcm

  [4000/30227]  13.2%  raw-images/train/PNEUMONIA/3c0f1edd-10c2-46da-a01c-a151aa88f2df.dcm

  [4100/30227]  13.6%  raw-images/train/NORMAL/3ca6b607-70d1-4aae-b5c1-9fd0d575ab8d.dcm

  [4200/30227]  13.9%  raw-images/train/PNEUMONIA/3d48f4d3-7a90-4ead-8634-b2d394575284.dcm

  [4300/30227]  14.2%  raw-images/train/PNEUMONIA/3df8778b-822d-4cae-8f94-9fe156c601b7.dcm

  [4400/30227]  14.6%  raw-images/train/PNEUMONIA/3ea67d3a-90be-4e77-a745-a9e323189097.dcm

  [4500/30227]  14.9%  raw-images/train/PNEUMONIA/3f432d6b-e0a2-4b46-ad7f-e42f713814ee.dcm

  [4600/30227]  15.2%  raw-images/train/PNEUMONIA/4007ffd5-5e8e-403d-8755-72ecaa2fce43.dcm

  [4700/30227]  15.5%  raw-images/train/NORMAL/40a9e10b-f872-4c72-a482-7187e2dca6ed.dcm

  [4800/30227]  15.9%  raw-images/test/PNEUMONIA/417553fa-ac96-4f78-bb07-e9e0d0c00ff2.dcm

  [4900/30227]  16.2%  raw-images/train/NORMAL/424f4f3b-345c-4f79-9b0b-028c20b74380.dcm

  [5000/30227]  16.5%  raw-images/train/NORMAL/4346c085-9210-43e2-8435-37653aecbe68.dcm

  [5100/30227]  16.9%  raw-images/test/NORMAL/44421e63-8523-4076-a84c-419361e28dde.dcm

  [5200/30227]  17.2%  raw-images/train/NORMAL/44ef3c88-24dd-422f-9999-167d382ad340.dcm

  [5300/30227]  17.5%  raw-images/test/NORMAL/45ca2f83-7941-425b-abdb-1a5a893439ad.dcm

  [5400/30227]  17.9%  raw-images/train/NORMAL/469481f9-b1cc-48f0-ab42-235e44cadb13.dcm

  [5500/30227]  18.2%  raw-images/test/PNEUMONIA/473cc35e-bf1d-4253-891e-5fab620cb47b.dcm

  [5600/30227]  18.5%  raw-images/train/NORMAL/48094385-2a86-48bd-9219-7f9cacdbb8ce.dcm

  [5700/30227]  18.9%  raw-images/val/PNEUMONIA/48eb6bcf-ddda-49f3-9f80-5a7a11b5bccc.dcm

  [5800/30227]  19.2%  raw-images/train/PNEUMONIA/49c04987-96af-4edb-b560-53c56a357cac.dcm

  [5900/30227]  19.5%  raw-images/train/NORMAL/4a8655a2-74d8-45c5-843a-0dcb32da9067.dcm

  [6000/30227]  19.8%  raw-images/train/NORMAL/4b597014-8d0b-41b1-bc33-e292b41e6e2c.dcm

  [6100/30227]  20.2%  raw-images/train/NORMAL/4c2d30a8-f815-4f71-b3cf-4a522f0f353e.dcm

  [6200/30227]  20.5%  raw-images/train/NORMAL/4cfc107d-1c1d-4e85-a2f1-237d0fc62f4c.dcm

  [6300/30227]  20.8%  raw-images/train/NORMAL/4dd92d1d-f5dd-4163-a55f-6a6ef95aa6f0.dcm

  [6400/30227]  21.2%  raw-images/train/NORMAL/4ea30da6-ddc8-4545-be9c-2c0f0b3f0de3.dcm

  [6500/30227]  21.5%  raw-images/test/NORMAL/4f67003c-b3b2-4055-ae99-650c5df64c85.dcm

  [6600/30227]  21.8%  raw-images/train/NORMAL/500a0bb1-131c-4b5f-8066-5de049daefc8.dcm

  [6700/30227]  22.2%  raw-images/train/NORMAL/50d770ba-9213-4377-909e-2e26e985875b.dcm

  [6800/30227]  22.5%  raw-images/train/NORMAL/51d905bb-48ae-4d6a-a69d-5a2aea153f59.dcm

  [6900/30227]  22.8%  raw-images/train/NORMAL/528c2d6b-bdd6-4c42-b100-4d0c30de0125.dcm

  [7000/30227]  23.2%  raw-images/train/NORMAL/536ba3bf-b867-4035-b483-35e9cbda9c0f.dcm

  [7100/30227]  23.5%  raw-images/train/NORMAL/54349eeb-01dd-4ddd-9f9b-f74d28a37524.dcm

  [7200/30227]  23.8%  raw-images/val/NORMAL/54fc4986-daf1-49c9-8309-0be488ebc9f8.dcm

  [7300/30227]  24.2%  raw-images/val/NORMAL/55ddd20e-3bb3-41e7-a931-973c40e3117b.dcm

  [7400/30227]  24.5%  raw-images/train/NORMAL/56b278f2-ab29-48b5-9602-b7ec496885df.dcm

  [7500/30227]  24.8%  raw-images/val/NORMAL/5789dc6b-fb03-4cbf-9b4e-add11f5b2850.dcm

  [7600/30227]  25.1%  raw-images/train/PNEUMONIA/58508fc2-0fd8-4c2a-87ee-a3bdda7cd9ff.dcm

  [7700/30227]  25.5%  raw-images/val/NORMAL/5916277a-cbd3-4bdf-a0cf-56fc667f9bc8.dcm

  [7800/30227]  25.8%  raw-images/val/NORMAL/59ffc415-e14b-47b2-86f1-07e41fee2846.dcm

  [7900/30227]  26.1%  raw-images/train/NORMAL/5aef8439-6fc5-45c0-9e52-1524f62a69f2.dcm

  [8000/30227]  26.5%  raw-images/test/NORMAL/5bcee483-ed6d-4e9c-b9db-1e48e5bb2403.dcm

  [8100/30227]  26.8%  raw-images/train/NORMAL/5c9364c7-51da-490b-82bd-e7078e9c21f2.dcm

  [8200/30227]  27.1%  raw-images/train/NORMAL/5d7886d1-6fdd-4bc7-9efe-613ac3dc034a.dcm

  [8300/30227]  27.5%  raw-images/train/NORMAL/5e5069e4-1f37-4fef-93d1-9b0162183277.dcm

  [8400/30227]  27.8%  raw-images/train/NORMAL/5f1febea-a061-4c0c-9932-49ff1616717c.dcm

  [8500/30227]  28.1%  raw-images/test/NORMAL/5fddbf25-9d69-435f-b803-9222e972e32b.dcm

  [8600/30227]  28.5%  raw-images/test/NORMAL/60b743c3-cf7f-4770-9926-ab3e8b76ecba.dcm

  [8700/30227]  28.8%  raw-images/train/NORMAL/6197bb45-7f5e-4579-beca-cbdbe1132d9a.dcm

  [8800/30227]  29.1%  raw-images/train/NORMAL/627fbbd0-5d32-4c2a-9aee-9859b309407b.dcm

  [8900/30227]  29.4%  raw-images/val/NORMAL/63396b9b-b228-4fe6-8aeb-5cd4862c15f5.dcm

  [9000/30227]  29.8%  raw-images/train/NORMAL/640ad2ae-b136-4e47-a86f-9ff3428e5ba4.dcm

  [9100/30227]  30.1%  raw-images/train/NORMAL/64cd1375-6d81-4200-be9f-afc1a7abe69d.dcm

  [9200/30227]  30.4%  raw-images/train/NORMAL/658da350-aa7a-4a04-b084-43a89e53259d.dcm

  [9300/30227]  30.8%  raw-images/train/NORMAL/66572a9d-0907-494b-8fe5-3d3771ab9455.dcm

  [9400/30227]  31.1%  raw-images/train/NORMAL/66ff514e-220e-4acd-97d7-1336a53feecd.dcm

  [9500/30227]  31.4%  raw-images/train/NORMAL/67d72432-8ea3-448c-943c-54d63a10701f.dcm

  [9600/30227]  31.8%  raw-images/train/PNEUMONIA/68d4ee73-479a-4e8c-beab-6822aa605a0f.dcm

  [9700/30227]  32.1%  raw-images/train/NORMAL/69897cf1-8690-47ea-a6ed-1853a52e9684.dcm

  [9800/30227]  32.4%  raw-images/train/NORMAL/6a56c65e-22ac-472e-b678-c75669deb4d9.dcm

  [9900/30227]  32.8%  raw-images/train/PNEUMONIA/6b013c90-ec73-4a7a-a607-17540c493e0f.dcm

  [10000/30227]  33.1%  raw-images/train/NORMAL/6bc29d1f-fdf7-4c3a-ab66-c99f60d27bb8.dcm

  [10100/30227]  33.4%  raw-images/train/NORMAL/6c7f1aae-7eda-4a03-9b3c-9bfd17ac953c.dcm

  [10200/30227]  33.7%  raw-images/train/NORMAL/6d3d7fb2-4059-4297-80ba-2756ab7494a0.dcm

  [10300/30227]  34.1%  raw-images/train/PNEUMONIA/6e028cf7-8ea4-4e7d-a2b5-0d5bd2eca495.dcm

  [10400/30227]  34.4%  raw-images/train/NORMAL/6ed46d56-93fa-4eda-be49-0b1a6c68ed75.dcm

  [10500/30227]  34.7%  raw-images/train/NORMAL/6f8f2795-cae9-4c41-9130-cd23fd840e7f.dcm

  [10600/30227]  35.1%  raw-images/train/NORMAL/707c724b-bc84-4e62-8a1e-195056b22f2a.dcm

  [10700/30227]  35.4%  raw-images/train/NORMAL/713da391-cee4-4241-82be-5d4db7f34645.dcm

  [10800/30227]  35.7%  raw-images/train/NORMAL/71e3ebac-7d73-4728-b23d-a7c0742ecdec.dcm

  [10900/30227]  36.1%  raw-images/val/PNEUMONIA/729c9ee1-d716-4b76-b5e7-690d6e914ea8.dcm

  [11000/30227]  36.4%  raw-images/train/NORMAL/736709ff-990d-4ba9-9b21-f9aaf542f5ce.dcm

  [11100/30227]  36.7%  raw-images/train/NORMAL/7426e930-fed6-4ef3-8a8f-4b70c12e94de.dcm

  [11200/30227]  37.1%  raw-images/train/NORMAL/74f427aa-a1bd-4eed-86de-2755158efcd9.dcm

  [11300/30227]  37.4%  raw-images/train/NORMAL/75c152a4-eebd-42ad-b642-98221a946b49.dcm

  [11400/30227]  37.7%  raw-images/val/NORMAL/76969629-8dc1-4091-9507-495fd53342dd.dcm

  [11500/30227]  38.0%  raw-images/test/NORMAL/77600a83-1710-4847-b7d9-2d1d6982e40c.dcm

  [11600/30227]  38.4%  raw-images/train/NORMAL/7845cd45-c899-4220-ab6d-e969ed2e1cf3.dcm

  [11700/30227]  38.7%  raw-images/train/NORMAL/78e409e6-a4df-4002-9068-3b3eef7b30b1.dcm

  [11800/30227]  39.0%  raw-images/train/NORMAL/79b34f64-0c0b-458b-82c3-95f938d3ab08.dcm

  [11900/30227]  39.4%  raw-images/val/PNEUMONIA/7a8dd22c-7af7-428c-a043-578390fc6fa1.dcm

  [12000/30227]  39.7%  raw-images/train/NORMAL/7b7ca7c2-9b4f-4370-9388-7ad0b2cdda63.dcm

  [12100/30227]  40.0%  raw-images/train/NORMAL/7c1dfc31-7068-4ec0-b722-8ae490c524ad.dcm

  [12200/30227]  40.4%  raw-images/train/NORMAL/7cf69a10-86d8-4933-9c97-b68b35d1a04d.dcm

  [12300/30227]  40.7%  raw-images/val/NORMAL/7dd3c24a-f0bf-4a6b-89c0-ccae17748457.dcm

  [12400/30227]  41.0%  raw-images/train/NORMAL/7e9a064b-33d7-4395-8244-d6bdb4dd0e2c.dcm

  [12500/30227]  41.4%  raw-images/train/NORMAL/7f5c524d-2d8f-4314-826d-10890906455a.dcm

  [12600/30227]  41.7%  raw-images/train/NORMAL/80121483-069a-4c36-8836-0dc41b14c786.dcm

  [12700/30227]  42.0%  raw-images/train/NORMAL/80ee782e-dd5c-4d8d-b030-6cb61322dd4a.dcm

  [12800/30227]  42.3%  raw-images/train/NORMAL/81bdc34f-f523-4228-a924-6f587daa70b7.dcm

  [12900/30227]  42.7%  raw-images/train/NORMAL/828ef404-6b29-46fd-a51b-11d18eaac71d.dcm

  [13000/30227]  43.0%  raw-images/test/NORMAL/8363d231-9345-4903-9b01-9fc3200792ea.dcm

  [13100/30227]  43.3%  raw-images/train/PNEUMONIA/84321b1c-3284-4ce4-89a7-fa42d6d9f997.dcm

  [13200/30227]  43.7%  raw-images/train/PNEUMONIA/8540e870-c8f7-494d-a779-a5fba52040b3.dcm

  [13300/30227]  44.0%  raw-images/test/NORMAL/85ffb2f7-51c3-4b6b-8e7d-d46af9ff82a8.dcm

  [13400/30227]  44.3%  raw-images/train/PNEUMONIA/86ed8bcd-55a0-4b91-8073-0cd11b77c907.dcm

  [13500/30227]  44.7%  raw-images/train/PNEUMONIA/87a3d945-d417-45a8-9f57-08cdb83e4e8b.dcm

  [13600/30227]  45.0%  raw-images/train/PNEUMONIA/88655da0-c331-4400-aedc-de357b57b35b.dcm

  [13700/30227]  45.3%  raw-images/train/PNEUMONIA/893b6861-0bfc-4e9f-94d4-3a967dda4223.dcm

  [13800/30227]  45.7%  raw-images/train/NORMAL/8a08f0a1-478c-4117-b2fd-80cc43850efa.dcm

  [13900/30227]  46.0%  raw-images/train/NORMAL/8ab479ea-10e6-48ac-94bd-f4eb3773fbb3.dcm

  [14000/30227]  46.3%  raw-images/val/NORMAL/8b6d0458-32b9-41a1-bab0-0adb2fa5bed4.dcm

  [14100/30227]  46.6%  raw-images/train/NORMAL/8c31e8da-4939-425d-802e-1c778a63d9ee.dcm

  [14200/30227]  47.0%  raw-images/train/NORMAL/8ce7c7e2-cf1c-4849-9a68-8d832c2b7e19.dcm

  [14300/30227]  47.3%  raw-images/test/NORMAL/8db6a182-ed54-415a-affc-eb6ab372d54d.dcm

  [14400/30227]  47.6%  raw-images/train/NORMAL/8e763690-1052-499f-abbb-7dd63e15149a.dcm

  [14500/30227]  48.0%  raw-images/train/NORMAL/8f2cdbe6-7e29-4c40-ba7f-54d3f64d10e6.dcm

  [14600/30227]  48.3%  raw-images/train/PNEUMONIA/90035195-09b5-4fc6-8cbc-f16bb0c26048.dcm

  [14700/30227]  48.6%  raw-images/train/NORMAL/90cef4f8-3198-4c71-96ac-ac3ed528908f.dcm

  [14800/30227]  49.0%  raw-images/train/NORMAL/91981606-e607-481d-af2b-c77dc9ede77a.dcm

  [14900/30227]  49.3%  raw-images/train/NORMAL/9280ca7a-4bc1-478a-90a8-09d87079f944.dcm

  [15000/30227]  49.6%  raw-images/train/NORMAL/934aab43-c449-4f2f-a468-b4d6eddae269.dcm

  [15100/30227]  50.0%  raw-images/train/NORMAL/93f992a4-8c0c-4d95-b141-1130e90e38ea.dcm

  [15200/30227]  50.3%  raw-images/train/NORMAL/94ca0f60-8ed8-482d-9531-1b302693a232.dcm

  [15300/30227]  50.6%  raw-images/train/NORMAL/95b1b8af-4dba-4904-a235-4165b8b11f23.dcm

  [15400/30227]  50.9%  raw-images/train/PNEUMONIA/96862a19-db35-4c6f-a6f4-2f00a1bd303d.dcm

  [15500/30227]  51.3%  raw-images/train/NORMAL/976f0494-b925-46fb-aee9-fb7897f83b24.dcm

  [15600/30227]  51.6%  raw-images/test/NORMAL/982fcd52-e4b7-4262-8361-069ca0c12148.dcm

  [15700/30227]  51.9%  raw-images/train/NORMAL/98f7df32-ac57-4e55-96d9-09066c77d542.dcm

  [15800/30227]  52.3%  raw-images/train/NORMAL/99ad8a84-90fd-460a-9818-263eab12ea0a.dcm

  [15900/30227]  52.6%  raw-images/test/PNEUMONIA/9a61bc75-01c7-496c-b5a9-b4ad264b7885.dcm

  [16000/30227]  52.9%  raw-images/train/NORMAL/9b43860f-c492-4da7-a930-1d4fbc9bc58b.dcm

  [16100/30227]  53.3%  raw-images/val/NORMAL/9c316b61-8635-4740-9fbf-5dc23c78490a.dcm

  [16200/30227]  53.6%  raw-images/train/PNEUMONIA/9d1ceb1a-66ef-4135-a905-3d7b51b0fb4d.dcm

  [16300/30227]  53.9%  raw-images/train/NORMAL/9df8b81f-7bde-4fd4-926d-cb08187f4866.dcm

  [16400/30227]  54.3%  raw-images/val/NORMAL/9ebdbeb1-2825-4a76-a23b-e51844753bf5.dcm

  [16500/30227]  54.6%  raw-images/train/NORMAL/9f8676ed-ec75-42d4-bb4d-304fcaace16d.dcm

  [16600/30227]  54.9%  raw-images/train/NORMAL/a05d6f9e-475b-4e47-b95b-45c6ac35e2b3.dcm

  [16700/30227]  55.2%  raw-images/train/NORMAL/a1214924-2cc5-481d-b329-bdacded69ff8.dcm

  [16800/30227]  55.6%  raw-images/train/NORMAL/a1dc7fe9-1e55-4956-9f04-f99f624faefb.dcm

  [16900/30227]  55.9%  raw-images/train/PNEUMONIA/a2b6217a-2c7b-4cc3-b313-ec48bf272a2f.dcm

  [17000/30227]  56.2%  raw-images/train/PNEUMONIA/a3729a13-c791-4f7b-bd48-fbaf4f7fc0e4.dcm

  [17100/30227]  56.6%  raw-images/train/NORMAL/a424f983-75af-44e1-84f6-6ef44f9580c5.dcm

  [17200/30227]  56.9%  raw-images/train/NORMAL/a4d5f354-2ea3-4a51-a03d-40d2a94f7780.dcm

  [17300/30227]  57.2%  raw-images/train/NORMAL/a598d06c-3131-4bd6-a6c7-5a0cca114065.dcm

  [17400/30227]  57.6%  raw-images/train/PNEUMONIA/a66d881d-c072-4ea0-a00c-74a62981a3e8.dcm

  [17500/30227]  57.9%  raw-images/test/NORMAL/a7189d7f-6d4e-4290-aceb-53a66ae0d090.dcm

  [17600/30227]  58.2%  raw-images/train/PNEUMONIA/a7caec7a-dd5a-48af-ab0e-817aa2617b9f.dcm

  [17700/30227]  58.6%  raw-images/train/NORMAL/a8a6c86e-43d2-42ee-bc72-b744888f88a5.dcm

  [17800/30227]  58.9%  raw-images/train/NORMAL/a961ccea-6d12-42a5-b788-d0a5633349a7.dcm

  [17900/30227]  59.2%  raw-images/train/PNEUMONIA/aa47c55a-7cf7-4105-9132-de080664f052.dcm

  [18000/30227]  59.5%  raw-images/train/PNEUMONIA/aafca7fa-b482-4e37-bbc4-96da4b744847.dcm

  [18100/30227]  59.9%  raw-images/train/NORMAL/aba15334-5b65-45bd-9849-e453de3129e2.dcm

  [18200/30227]  60.2%  raw-images/train/PNEUMONIA/ac4bf897-0752-4095-9404-1e6ff42a1dfb.dcm

  [18300/30227]  60.5%  raw-images/train/PNEUMONIA/acee926a-5141-461f-b0c7-edbbf8bf51c8.dcm

  [18400/30227]  60.9%  raw-images/train/PNEUMONIA/ada57dae-a677-4d5e-a9b5-1143893e9154.dcm

  [18500/30227]  61.2%  raw-images/train/PNEUMONIA/ae657240-1b69-4b1d-af95-673af661fecf.dcm

  [18600/30227]  61.5%  raw-images/train/NORMAL/af06dfe8-ee19-4097-9129-95cbdb6929e5.dcm

  [18700/30227]  61.9%  raw-images/test/PNEUMONIA/afc7efe2-5df9-4274-8df4-31eefde7b574.dcm

  [18800/30227]  62.2%  raw-images/train/NORMAL/b05be23b-9b1d-4868-ae6c-72485cd2c601.dcm

  [18900/30227]  62.5%  raw-images/val/NORMAL/b10b52da-84fd-4057-b675-330e46c53504.dcm

  [19000/30227]  62.9%  raw-images/train/PNEUMONIA/b1976cfc-3bae-4bae-a968-4892e6f953ca.dcm

  [19100/30227]  63.2%  raw-images/val/PNEUMONIA/b2521978-0df6-4fd5-b684-f03b1b96dbf7.dcm

  [19200/30227]  63.5%  raw-images/train/PNEUMONIA/b3026aa2-14f4-4648-9261-c114f149f0d3.dcm

  [19300/30227]  63.9%  raw-images/train/NORMAL/b3c66cb2-3aa5-4b2f-ba06-19ea7c5efde2.dcm

  [19400/30227]  64.2%  raw-images/train/PNEUMONIA/b44b65e1-7382-4aa6-8d87-fe6d7b4f1a17.dcm

  [19500/30227]  64.5%  raw-images/train/NORMAL/b4ea3ed4-ba8e-4b62-8150-72e39aef9055.dcm

  [19600/30227]  64.8%  raw-images/train/PNEUMONIA/b58e15a4-085f-4d55-91e6-7d219ff570b5.dcm

  [19700/30227]  65.2%  raw-images/train/PNEUMONIA/b6468969-2e9b-4a36-aaa0-2c77b205105e.dcm

  [19800/30227]  65.5%  raw-images/train/NORMAL/b6fe8b37-db6d-4ab9-b8bc-401a5e2b35a2.dcm

  [19900/30227]  65.8%  raw-images/train/NORMAL/b7b167ec-a640-4127-90c6-56ac2e9a4bdb.dcm

  [20000/30227]  66.2%  raw-images/train/NORMAL/b848084c-ca9f-48b7-865b-3a1761fd9775.dcm

  [20100/30227]  66.5%  raw-images/train/NORMAL/b9081e46-c32d-4a93-9eeb-2eb9e195d0c5.dcm

  [20200/30227]  66.8%  raw-images/train/PNEUMONIA/b9b618f9-89f8-4a4d-8eff-ccbf4bef0b16.dcm

  [20300/30227]  67.2%  raw-images/train/PNEUMONIA/ba395818-6a27-4185-98ca-a51c4c70b2d5.dcm

  [20400/30227]  67.5%  raw-images/train/NORMAL/badba1fe-003c-4792-817f-ef8bfc22c27d.dcm

  [20500/30227]  67.8%  raw-images/train/NORMAL/bb7ad574-8d57-428a-9756-7d9197c989d8.dcm

  [20600/30227]  68.2%  raw-images/train/NORMAL/bc405e86-e604-4c34-a6ea-32460f370967.dcm

  [20700/30227]  68.5%  raw-images/train/PNEUMONIA/bcbcf3f5-244b-4979-9405-9cfe410b37a7.dcm

  [20800/30227]  68.8%  raw-images/train/PNEUMONIA/bd7b4e6e-5384-4cce-9732-0dd7f9d15da8.dcm

  [20900/30227]  69.1%  raw-images/train/NORMAL/be16ff6b-cb15-424f-91ed-ff6612110961.dcm

  [21000/30227]  69.5%  raw-images/train/NORMAL/beb82683-d192-4b2d-81ad-a6940e977be3.dcm

  [21100/30227]  69.8%  raw-images/train/NORMAL/bf5d1ee4-a9e2-4648-8734-58d150fa1eeb.dcm

  [21200/30227]  70.1%  raw-images/train/NORMAL/bfe43bfd-5d99-4216-83da-f0e6e918fe28.dcm

  [21300/30227]  70.5%  raw-images/train/PNEUMONIA/c241425c-418c-4958-8a18-c3425fe03f03.dcm

  [21400/30227]  70.8%  raw-images/train/PNEUMONIA/c2ee643f-0568-4816-9fa5-19d50cde5386.dcm

  [21500/30227]  71.1%  raw-images/test/NORMAL/c39f0844-5e0c-4585-b05b-140caec4e078.dcm

  [21600/30227]  71.5%  raw-images/train/PNEUMONIA/c4328895-fac4-4ecc-b164-88f77dee37ca.dcm

  [21700/30227]  71.8%  raw-images/test/PNEUMONIA/c4e96c53-34f7-4607-bab4-45e982079b2b.dcm

  [21800/30227]  72.1%  raw-images/train/NORMAL/c5b0ade4-6a46-44b1-aa80-d07913e41ea6.dcm

  [21900/30227]  72.5%  raw-images/train/NORMAL/c66a387d-051d-41bd-981c-3be82e53dc5a.dcm

  [22000/30227]  72.8%  raw-images/train/NORMAL/c7650373-fd88-4a09-9f59-721738379af1.dcm

  [22100/30227]  73.1%  raw-images/train/NORMAL/c81ae60a-eb3c-4c01-82f2-af0889093f5b.dcm

  [22200/30227]  73.4%  raw-images/train/NORMAL/c8e8c3ff-52e1-44bb-84b0-e2a90ffcfd32.dcm

  [22300/30227]  73.8%  raw-images/test/NORMAL/c9c114a1-5ddf-4460-855c-25dac3ae7289.dcm

  [22400/30227]  74.1%  raw-images/train/NORMAL/ca8ab192-068e-4653-84eb-e4ff6f60d4ab.dcm

  [22500/30227]  74.4%  raw-images/test/NORMAL/cb67e947-3b76-4a29-b818-8993c8971f09.dcm

  [22600/30227]  74.8%  raw-images/train/NORMAL/cc243a7f-1947-4a97-af61-f74948cd8bff.dcm

  [22700/30227]  75.1%  raw-images/train/NORMAL/ccee8914-7408-422f-9800-c86f5e906939.dcm

  [22800/30227]  75.4%  raw-images/train/NORMAL/cdaa0581-af7a-43d9-b6fd-3874dcde34e6.dcm

  [22900/30227]  75.8%  raw-images/train/NORMAL/ce8b83d0-dc04-45de-bfa1-bc67b24303a6.dcm

  [23000/30227]  76.1%  raw-images/train/NORMAL/cf5e0fac-1011-4865-8c9b-0ecfcc748c3b.dcm

  [23100/30227]  76.4%  raw-images/train/NORMAL/d033b43a-a7c4-4ded-b2c1-000d41c6f2cc.dcm

  [23200/30227]  76.8%  raw-images/val/NORMAL/d0f3dd8b-a619-407e-95ff-b6bb1a0581bf.dcm

  [23300/30227]  77.1%  raw-images/train/NORMAL/d1d814f0-b094-47c2-aae7-6d24aae6ccd7.dcm

  [23400/30227]  77.4%  raw-images/train/PNEUMONIA/d29caa55-2027-4078-8d93-c6aaa25f7044.dcm

  [23500/30227]  77.7%  raw-images/train/PNEUMONIA/d3a0da1a-8289-4fca-ae3c-6894d4f3c108.dcm

  [23600/30227]  78.1%  raw-images/train/NORMAL/d4911016-ade1-4a4c-86b2-7fc3dffb326a.dcm

  [23700/30227]  78.4%  raw-images/train/PNEUMONIA/d5523ffc-1c8a-4250-939a-3f5215397ff2.dcm

  [23800/30227]  78.7%  raw-images/train/NORMAL/d61b2d8e-2cb1-430b-8bfd-2df014aadfae.dcm

  [23900/30227]  79.1%  raw-images/train/NORMAL/d6f224ef-4143-4af7-a164-f7b1ad68e8d9.dcm

  [24000/30227]  79.4%  raw-images/train/NORMAL/d7b458c6-bb21-41de-b180-968824348270.dcm

  [24100/30227]  79.7%  raw-images/val/NORMAL/d8b1ef8b-36d0-4f3d-affa-f9f1fdbacd10.dcm

  [24200/30227]  80.1%  raw-images/val/NORMAL/d97e5889-7104-475b-bf38-69b04157515c.dcm

  [24300/30227]  80.4%  raw-images/train/NORMAL/da4d442b-bd4a-4703-9180-f437a5129444.dcm

  [24400/30227]  80.7%  raw-images/train/NORMAL/db4601ab-e3a4-4f94-be20-65607e00aa6e.dcm

  [24500/30227]  81.1%  raw-images/val/NORMAL/dc1ff256-d678-4d7d-b4b9-6254ed110f4b.dcm

  [24600/30227]  81.4%  raw-images/train/NORMAL/dd086446-9635-46bc-aa01-546188266938.dcm

  [24700/30227]  81.7%  raw-images/test/NORMAL/dddcf2da-dc3a-4d1c-98b1-2ae1a2670e3f.dcm

  [24800/30227]  82.0%  raw-images/train/NORMAL/dec13d78-ab5e-43c4-86f9-1567c18b8a4e.dcm

  [24900/30227]  82.4%  raw-images/train/NORMAL/df87a24a-0da2-4ac4-98bc-52b949571900.dcm

  [25000/30227]  82.7%  raw-images/val/NORMAL/e044f178-b1f8-4ab7-b9c4-fa67678160f1.dcm

  [25100/30227]  83.0%  raw-images/train/NORMAL/e118d121-0791-4250-87a7-8488c7f66b0d.dcm

  [25200/30227]  83.4%  raw-images/train/PNEUMONIA/e1eb1f53-a6e1-461d-96bc-ca7fd48b8836.dcm

  [25300/30227]  83.7%  raw-images/train/PNEUMONIA/e2cb1c89-244e-407f-9798-9a9670616850.dcm

  [25400/30227]  84.0%  raw-images/train/NORMAL/e3a1a1c3-bb46-4ba9-aec9-7b59b96cd728.dcm

  [25500/30227]  84.4%  raw-images/train/NORMAL/e470b835-92bb-480b-8905-5d6ea3f1827b.dcm

  [25600/30227]  84.7%  raw-images/train/NORMAL/e532aa3b-ffb3-40e6-9403-7aadb2e8278b.dcm

  [25700/30227]  85.0%  raw-images/train/PNEUMONIA/e5ee965b-7a79-4ceb-986c-a775a3c1d7a8.dcm

  [25800/30227]  85.4%  raw-images/val/PNEUMONIA/e6a3f420-39d4-4042-8485-87024e7fb4f3.dcm

  [25900/30227]  85.7%  raw-images/train/PNEUMONIA/e77e5857-d114-484b-acbb-9736ffb750c3.dcm

  [26000/30227]  86.0%  raw-images/val/NORMAL/e84a5323-c1fb-442a-a9ce-73ed42dbc61a.dcm

  [26100/30227]  86.3%  raw-images/train/PNEUMONIA/e92d7e53-f191-41af-a86b-8da6c7734386.dcm

  [26200/30227]  86.7%  raw-images/train/NORMAL/ea16d87a-1406-46fe-af11-31c97cccc698.dcm

  [26300/30227]  87.0%  raw-images/train/PNEUMONIA/eadbf3c9-f034-4b29-9a46-b90a16978a2a.dcm

  [26400/30227]  87.3%  raw-images/train/NORMAL/eb9725a7-dce6-4144-bb0a-09a825e2d8fe.dcm

  [26500/30227]  87.7%  raw-images/test/NORMAL/ec4126de-1712-4507-8ed1-59662058375b.dcm

  [26600/30227]  88.0%  raw-images/test/NORMAL/ecf5754d-1c05-4471-94b4-4dbb20f938bc.dcm

  [26700/30227]  88.3%  raw-images/train/NORMAL/edb48e75-2fc4-40dc-9f8c-3bee804377a5.dcm

  [26800/30227]  88.7%  raw-images/train/NORMAL/eea3a106-1e1a-4f1d-85c3-f1575fcd13b7.dcm

  [26900/30227]  89.0%  raw-images/test/NORMAL/ef702b60-9b45-4d6c-b392-2acf1835c64d.dcm

  [27000/30227]  89.3%  raw-images/train/PNEUMONIA/f0343afa-3b37-47d4-93d0-9ee56c30952e.dcm

  [27100/30227]  89.7%  raw-images/train/NORMAL/f11dbfda-c5fb-4312-90b2-6775d6489fc3.dcm

  [27200/30227]  90.0%  raw-images/train/PNEUMONIA/f1c0e838-08dd-4ec4-84a7-cedf9b87f592.dcm

  [27300/30227]  90.3%  raw-images/train/NORMAL/f281eb27-ff81-4223-9f5c-b3e49a9a7b08.dcm

  [27400/30227]  90.6%  raw-images/val/NORMAL/f35a1f9e-7b65-42cf-9678-7696737108c4.dcm

  [27500/30227]  91.0%  raw-images/train/PNEUMONIA/f4362a52-b9f5-4d96-a6ba-04284a233eb0.dcm

  [27600/30227]  91.3%  raw-images/train/NORMAL/f51d825e-be93-4428-bcd6-3feedc5ffe61.dcm

  [27700/30227]  91.6%  raw-images/train/PNEUMONIA/f5cb4b26-5821-4b91-90a0-629f4f0cbd2f.dcm

  [27800/30227]  92.0%  raw-images/train/NORMAL/f6a05a24-1cd8-4eb1-ad7c-5d5fd5d885be.dcm

  [27900/30227]  92.3%  raw-images/train/PNEUMONIA/f77b0afe-0085-4ee0-afad-a1e9fda8fe65.dcm

  [28000/30227]  92.6%  raw-images/train/NORMAL/f85835b4-bf19-4055-b3ad-82edd40cb96c.dcm

  [28100/30227]  93.0%  raw-images/train/PNEUMONIA/f92793eb-6396-4597-ad39-2cc6e8eff84b.dcm

  [28200/30227]  93.3%  raw-images/val/NORMAL/f9bf4d68-b885-4fea-9702-77924abf06eb.dcm

  [28300/30227]  93.6%  raw-images/train/NORMAL/fa9279e7-29b5-4997-b30d-dcfa0a3ba47f.dcm

  [28400/30227]  94.0%  raw-images/val/NORMAL/fb679675-c42d-4c9f-9006-456eaa860e1d.dcm

  [28500/30227]  94.3%  raw-images/train/NORMAL/fc355455-f89c-4203-97da-50f007c2b7d8.dcm

  [28600/30227]  94.6%  raw-images/train/PNEUMONIA/fcf5cd90-1a5d-4e45-925e-ff82dcbdc0ad.dcm

  [28700/30227]  94.9%  raw-images/train/NORMAL/fdd7ad70-be5f-4927-95ee-e6d4c05c9bdb.dcm

  [28800/30227]  95.3%  raw-images/val/NORMAL/fe9ba80f-ccb3-4de8-9f6b-610f814067d2.dcm

  [28900/30227]  95.6%  raw-images/train/NORMAL/ff551276-6116-4e99-aeb8-e59eb8f6ce0a.dcm

  [29000/30227]  95.9%  raw-images/test/PNEUMONIA/0022073f-cec8-42ec-ab5f-bc2314649235.dcm

  [29100/30227]  96.3%  raw-images/train/PNEUMONIA/03e4827c-7338-4de3-9ac6-8831ba5637e9.dcm

  [29200/30227]  96.6%  raw-images/train/NORMAL/0e266ced-46fe-4868-8a5a-ef1be71d8f9a.dcm

  [29300/30227]  96.9%  raw-images/test/NORMAL/10e2a82e-57bd-480e-9b69-e4ec1565b0ab.dcm

  [29400/30227]  97.3%  raw-images/test/NORMAL/149173ac-662a-4883-834d-43ff97a29b18.dcm

  [29500/30227]  97.6%  raw-images/train/NORMAL/1b52079c-b9ef-42d3-9e9a-17aea3bc6031.dcm

  [29600/30227]  97.9%  raw-images/train/PNEUMONIA/1e6c28f1-f8d3-4d49-bb82-0cc8709a86f1.dcm

  [29700/30227]  98.3%  raw-images/train/NORMAL/224a054f-8497-4e62-b4fe-b7829c62879e.dcm

  [29800/30227]  98.6%  raw-images/val/PNEUMONIA/25e49cde-cdd9-47ba-9e3c-bc8406433240.dcm

  [29900/30227]  98.9%  raw-images/val/PNEUMONIA/29000617-ac33-40a4-ac5c-19fb586edb69.dcm

  [30000/30227]  99.2%  raw-images/train/PNEUMONIA/2c9a388f-0042-4b88-b52b-ea0b21fb7960.dcm

  [30100/30227]  99.6%  raw-images/train/NORMAL/2faeab4f-17bf-410e-99b9-77bf4ae75963.dcm

  [30200/30227]  99.9%  raw-images/train/PNEUMONIA/c1415e26-fddf-4a0c-a7eb-7b9a0d9e9983.dcm

  [30227/30227] 100.0%  raw-images/train/PNEUMONIA/c1f7889a-9ea9-4acb-b64c-b737c929599a.dcm

Done. Uploaded 30227 files.

---

**Done.** Both datasets now live under `s3://pneumonia-data-set-group-4/raw-images/`, organized as `<source>/<split>/<label>/<file>`. Next step: `data_preperations.ipynb` for the preprocessing pipeline.